version: '3.8'
services:
  app:
    image: node:18.15 #LTS
    working_dir: /node/src/app
    volumes:
      - .:/node/src/app
    ports:
      - "3333:3333"
    command:
      # yarn dev
      # npm run dev --watch
      "tail -f /dev/null"
